
export const createUserUrl              = "/api/v3/users/admin"
export const accountBalanceUrl          = "/api/account/balance"
export const adminLoginUrl              = "/api/v3/users/admin/signin"
export const adminListUrl               = "/api/v3/users/admin/list"
export const roleListUrl                = "/api/v3/users/role/list"
export const allTotalListUrl            = "/api/v3/users/admin/alltotalList"
export const dailyReportUrl             = "/api/v3/users/admin/dailyReport"
export const adminHeaderDashboardUrl    = "/api/v3/users/admin/headerdashboard"
export const balanceUpdateUrl           = "/api/v3/payments/updateBalance1"
export const gameLogUrl                 = "/api/v3/users/history/gamelog"
export const userBalanceUrl             = "/api/v2/users/get-balance/"
export const userSessionUrl             = "/api/v3/users/session/list"
export const userDeleteSessionUrl       = "/api/v3/users/session/"